### PR TITLE
Address the Deficiency at Resource Type and Resource Selection Logic in ResourceDetails1 Component

### PR DESCRIPTION
**Pull request by kubraaksux**
**_Overview:_**

This Pull Request introduces significant updates to the ResourceDetails1 component, enhancing the resource type selection functionality. The key improvements focus on integrating category tree data for both material and human resources and refining the user interaction process.

**_Key Updates:_**

Exclusive Selection Logic: Implemented logic to exclusively select either a material or a human resource. Selecting one type automatically deselects the other, ensuring that only one resource type can be chosen at any given time.

State Management Improvements: The component's state management was updated to effectively handle the new selection logic. This includes using state hooks to track the user's selection and updating the UI accordingly.

Updated useQuery Calls: Modified the useQuery calls to fetch data for both material and human resources from getCategoryTree. This aligns with the latest react-query syntax and ensures seamless data fetching and backend integration.

UI Enhancements: Adjusted the user interface to reflect the integration of category tree data for both resource types. This includes conditional rendering and dynamic population of the Select components based on the resource type selected.

**_Testing and Validation:_**

Conducted manual testing to confirm the correct functionality of the exclusive selection mechanism between material and human resources.
Verified that the component's state accurately updates based on the user's selection, properly reflecting the chosen resource type.

Instructions for Testing:
Navigate to the ResourceDetails1 component.
Select either a material or a human resource option.
Observe that selecting one type will automatically deselect the other.
Ensure that only one resource within the selected type can be chosen and that the selection is correctly reflected in the component's state.

Additional Notes:
The integration with getCategoryTree for both resource types represents a comprehensive approach to resource management, offering a more dynamic and user-friendly interface.

### CODE REVIEW

**Comment by kubraaksux** [comment]
**_CURRENT:_**

Screenshot 2023-12-18 at 23 09 38

Screenshot 2023-12-18 at 23 09 59

Screenshot 2023-12-18 at 23 10 31

**_PREVIOUS_**

Screenshot 2023-12-18 at 23 11 29

Screenshot 2023-12-18 at 23 11 45

**Comment by kubraaksux** [comment]
At previous version, there was an import for category tree, i didn't find it relevant but since @ilgazer implemented the category tree, revision from him is needed.

**Comment by kubraaksux** [comment]
I have discussed with @ilgazer and @alitpc25 about category tree and its implementation is finalized. Category Tree for Human resources also implemented. Now both human and material resources fully implemented and integrated. 

Screenshot 2023-12-18 at 23 40 16

**Comment by kubraaksux** [comment]
solved here [issue #570 ](https://github.com/bounswe/bounswe2023group1/issues/570)

**Comment by ilgazer** [comment]
Thank you for addressing this kübra. It works nicely

**Comment by orkana** [comment]
Works great

**Pull request merged**
