### PR TITLE
Enhanced annotation logic for Date and Geographical Data and Additional Metadata

### PR DESCRIPTION
**Pull request by kubraaksux**
This PR introduces significant enhancements to the annotation display in our map interface. Previously, annotations lacked depth and clarity, resulting in a suboptimal user experience. To address this, we've implemented a comprehensive approach to showcase annotations more effectively.

Enhanced Readability: We've restructured the annotation display to ensure that key information is easily accessible and readable. This makes it straightforward for users to grasp the essential details at a glance.

Rich Data Presentation: Annotations now include date and geographical data, adding contextual relevance to each marker. This enhancement allows users to connect more meaningfully with the information presented.

Additional Metadata Integration: To further enrich the user experience, we've incorporated the display of additional metadata within annotations. This provides users with a more rounded and detailed understanding of each annotation.

Interactive and Engaging Display: The new annotation logic brings an interactive element to the map, encouraging users to explore and engage with the content more deeply.

Impact:

These improvements significantly elevate the effectiveness of our map's annotation system. By presenting information in a more structured and detailed manner, we enhance user engagement and provide a more intuitive and informative experience.

### CODE REVIEW

**Comment by kubraaksux** [comment]
Screenshot 2023-11-27 at 11 14 54

**Comment by kubraaksux** [comment]
previous: 

Screenshot 2023-11-27 at 03 25 40

current:

Screenshot 2023-11-27 at 11 07 19

**Comment by kubraaksux** [comment]
Geolocation information is sustained. Reverse geocoding for human readable format of locations were implemented at [#PR 382](https://github.com/bounswe/bounswe2023group1/pull/382). I have updated and adapted it for the use of annotations, resource cards and request cards. Previously it was implemented but then even if it was merged, code was lost. I found it from previous branches and implemented again. Its implementation was repetitively, and it was not completely suitable for current purposes and code, so i revised and reimplemented it. Now it works perfect

**Comment by kubraaksux** [comment]
Screenshot 2023-11-27 at 15 58 41

i have increased mock data, also now we can see annotations of health center places, sheltering camps, or any other disaster response areas. 
Furthermore, we can also see geolocations of them.

**Comment by ilgazer** [comment]
I removed the following dependencies as they were both unused and breaking the npm install.

```
"@mui/styles": "^5.14.18"
"@mui/joy": "^5.0.0-beta.15"
"@mui/lab": "^5.0.0-alpha.153"
```

**Comment by kubraaksux** [comment]
Screenshot 2023-11-27 at 18 17 37

Screenshot 2023-11-27 at 18:17:48
Screenshot 2023-11-27 at 18:09

This feature emphasizes the annotation features. Moreover, users can get in-depth information with a focus on the facility. This will be helpful for victims in the disaster response moment

**Comment by kubraaksux** [comment]
it was working correctly and completely before the merge

**Pull request merged**
