### PR TITLE
Directionsapi

### PR DESCRIPTION
**Pull request by alitpc25**
Frontend and backend connections and backend-database connections are handled. So, docker-compose up is enough to start the whole container.

### CODE REVIEW

**Comment by ilgazer** [comment]
This somehow regresses all the changes merged from #185 To solve this, I am mergeing the nginx changes back into the directionsapi branch. We can merge it with dev afterwards.

**Comment by ilgazer** [comment]
You unrolled #185 in the commit "update docker-compose and package.json to run all application alltogether with a single docker-compose up command". I am undoing that and then mergeing.

**Comment by ilgazer** [comment]
@alperenDagi Thanks for testing the last version of the PR!

**Review by ilgazer — APPROVED** [review]
The last version seems to work. I feel like it's ready to be merged.

**Review by alperenDagi — APPROVED** [review]
Thanks Ilgaz.

**Pull request merged**
