### PR TITLE
Implement category trees and integrate with backend for map page. Add victim page with quick add need

### LINKED ISSUE #374: Frontend Tie Map to Backend
Make the map pull the data from the backend instead of mock data

### PR DESCRIPTION
**Pull request by ilgazer**
close #374 #416 #486

This PR migrates the mock data formats to the backend data format. Furthermore, category tree support is added for displaying item names, as well as filtering by supercategories in the category selector. Furthermore, the map demo page was converted into a generic map page, and a victim map page with quick add need was implemented.

This PR adds the dependency react-query.

This PR addresses the following requirements:

1.1.2.1.3. Victims shall be able to view assistance locations on a map and as a list. (Help centres, soup kitchens etc.)
1.1.2.1.4. Victims shall be able to filter the assistance locations by type and distance.
1.1.2.1.5. Victims shall be able to view available resources on a map and as a list.
1.1.2.1.6. Victims shall be able to filter resources by name, category and distance.
1.1.2.1.7. Victims shall be notified when a relevant assistance location is nearby.
1.2.7.1. The platform shall have a map interface that displays the appropriate subset of resources, requests, and tasks, along with warnings related to the current situation.
1.2.7.2. The map shall be capable of filtering items by the applicable subset of name, category, amount, distance, urgency and status.

### CODE REVIEW

**Comment by ilgazer** [comment]
I successfully merged dev. As the zoom feature in #474 was not working, it was rolled back. The PR is now ready for merge.

**Comment by ilgazer** [comment]
@kubraaksux was the zoom feature working before? I couldn't get it to work so I assumed it was broken

**Comment by kubraaksux** [comment]
it was working ofc as i wrote. why to merge not working? check conflicts, we have talked this with you before your commit here so you are already very aware it was working. this is the second time you are doing that, playing blind.

**Comment by kubraaksux** [comment]
those are implemented at another pr. Are you sure this description is not repetetive?
1.1.2.1.3. Victims shall be able to view assistance locations on a map and as a list. (Help centres, soup kitchens etc.)
1.1.2.1.4. Victims shall be able to filter the assistance locations by type and distance.
1.1.2.1.5. Victims shall be able to view available resources on a map and as a list.
1.1.2.1.6. Victims shall be able to filter resources by name, category and distance.

[PR #469 ](https://github.com/bounswe/bounswe2023group1/pull/469)

**Pull request merged**
