### PR TITLE
Feature/frontend text annotation

### LINKED ISSUE #543: Investigate annotations and decide on annotation format
As per customer requests, we need to be able to annotate requests, needs, actions etc. As a part of this, we will need to decide what annotation fields we will use. The product of this issue will guide the work in #541 and #542

### PR DESCRIPTION
**Pull request by ilgazer**
Implemented displaying text annotations on Warning, Resource and Need cards. Further implemented adding new annotations and editing old ones. As the backend for annotations are still a work in progress, the annotations are stored locally. This PR partially resolves #543, #541, and #542. Future work on implementing image annotations and annotations containing images remain.

image
image

### CODE REVIEW

**Comment by kubraaksux** [comment]
@ilgazer there seems so much conflicts! You should push to dev, not main.

**Comment by kubraaksux** [comment]
It seems you have force-pushed, it is better not to do it especially here!!

**Comment by kubraaksux** [comment]
Yeah, now it is better! Let's work on dev. And everything seems great. Good job!!

**Comment by ilgazer** [comment]
@kubraaksux thanks for catching my "main" oversight! I intentionally did a force push, as my previous merge from dev into this branch had some weird side effects. I decided that the best way to rectify that without polluting the git tree was to re-do the merge and then force push to overwrite the old one.

**Comment by ilgazer** [comment]
Thanks for the quick checking!

**Comment by kubraaksux** [comment]
Thats a great solution! You're welcome. 

> @kubraaksux thanks for catching my "main" oversight! I intentionally did a force push, as my previous merge from dev into this branch had some weird side effects. I decided that the best way to rectify that without polluting the git tree was to re-do the merge and then force push to overwrite the old one.

**Comment by kubraaksux** [comment]
> Thanks for the quick checking!

Alwaysss!!

**Pull request merged**
