### PR TITLE
sign in and sign up update

### PR DESCRIPTION
**Pull request by kubraaksux**
sign in and sign up updated.
- design changes
- use email instead of the phone number. group decision

### CODE REVIEW

**Comment by ilgazer** [comment]
@kubraaksux can you check if I solved the merge conflict successfully. If so, we can merge

**Comment by kubraaksux** [comment]
it works, thanks

**Comment by kubraaksux** [comment]
Screenshot 2023-11-03 at 02 31 54

**Comment by kubraaksux** [comment]
Screenshot 2023-11-03 at 02 32 15
Screenshot 2023-11-03 at 02 32 28

**Comment by kubraaksux** [comment]
Screenshot 2023-11-03 at 02 32 38
Screenshot 2023-11-03 at 02 32 51
Screenshot 2023-11-03 at 02 33 01
Screenshot 2023-11-03 at 02 33 12

**Pull request merged**
