### PR TITLE
Feature/frontend account

### PR DESCRIPTION
**Pull request by kubraaksux**
account for profile is implemented. user can update their info at the profile such as gender, blood type, country, email vs... also can make a request for user role.

### CODE REVIEW

**Comment by kubraaksux** [comment]
account improved, copyrights edited and managed to center at center of the bottom of page. navigations updated. still need main dashboard to fully cover all existing and necessary navigations.

**Comment by ilgazer** [comment]
Looks good! I will resolve the merge conflict and merge.

**Comment by ilgazer** [comment]
@kubraaksux can you verify that everything works still. I tested it but don't want to miss anything

**Comment by kubraaksux** [comment]
it works fine

**Comment by kubraaksux** [comment]
> Looks good! I will resolve the merge conflict and merge. Just one thing, could you add some screenshots for next time?

Yeah, sure!

**Comment by kubraaksux** [comment]
Screenshot 2023-11-03 at 02 21 29

**Comment by kubraaksux** [comment]
Screenshot 2023-11-03 at 02 21 57
Screenshot 2023-11-03 at 02 23 06

**Pull request merged**
