### PR TITLE
Translation api

### PR DESCRIPTION
**Pull request by volcaniqueo**
I implemented Google Translation API.

### CODE REVIEW

**Comment by volcaniqueo** [comment]
will resolve the conflicts and open again

**Comment by volcaniqueo** [comment]
All fine, ready to merge!

**Comment by alperenDagi** [comment]
There is still conflict in App.js file . Please change it manually.

**Review by alperenDagi — CHANGES_REQUESTED** [review]
Still contains conflict in App.js. Please resolve it manually.

**Comment by volcaniqueo** [comment]
> Still contains conflict in App.js. Please resolve it manually.

I resolved it. Problem was that Imbd Api has also been included to dev branch after I sent the request. Thank you!

**Pull request merged**
